### ISSUE TITLE
Please handle issues help - 

### ISSUE THREAD

**Issue by violetmoonlight** [blockchain/My-Wallet-V3-iOS#7]
Please handle issues help - 
![zalo_screenshot_7_2_2016_1634778](https://cloud.githubusercontent.com/assets/17107796/12879639/c402954e-ce68-11e5-885b-6b97e6929a7a.png)
![zalo_screenshot_7_2_2016_1636228](https://cloud.githubusercontent.com/assets/17107796/12879640/c406b020-ce68-11e5-99da-d023b9d66498.png)

why the same line, the outside and inside are not the same
why time confirmation so long, has one day before
thanks for watching email

**Comment by woudini** [comment]
The values -0.0001 and 0.2435765 are not the same because the 0.2435765 BTC was received to the same address it was sent from. So the actual amount sent was 0.2435765 BTC, but because it's the same address, the net loss is the fee that was paid (0.0001 BTC).

Confirmation seems to be taking long because of the dust output that was generated (0.00000001 BTC). https://blockchain.info/tx/055956d9629b9f704955ce4dd86dadcd9126a35da85099153450a8ee3a719c3a

How exactly was this transaction created, and what were you trying to accomplish with it? Did you use a blockchain.info wallet?
